/**
 * Admin OS BuildX — Phase 2: link cards to existing tools + read-only summary keys.
 * Backend APIs unchanged (/api/v1/*). Stub = no dedicated tool yet.
 */

export const ADMIN_OS_TAB_ORDER = [
  'dealers',
  'dealer-operations',
  'leads',
  'content',
  'reports',
  'users',
  'support',
  'settings',
];

/** Old admin sidebar tools — embedded in shell (same pages / APIs). */
export const ADMIN_OS_LEGACY_LINKS = [
  { id: 'search-governance', label: 'Search QA', href: '/search-governance' },
  { id: 'blog', label: 'Blog', href: '/blog' },
  { id: 'users', label: 'Users', href: '/users' },
  { id: 'dealer-beta', label: 'Dealer Beta', href: '/dealer-beta' },
  { id: 'dealer-bootstrap', label: 'Dealer Bootstrap', href: '/dealer-bootstrap' },
  { id: 'catalog', label: 'Vehicles (Data Ops)', href: '/catalog' },
];

export const ADMIN_OS_TABS = {
  dealers: {
    id: 'dealers',
    label: 'Dealers',
    icon: '▦',
    description: 'Manage dealer records, profiles, locations, contacts, visibility, and status.',
    route: '/admin/dealers',
    pills: ['All Dealers', 'Active', 'Pending', 'Hidden'],
    ai: 'Ask Admin OS about dealers, profile status, locations, or recent activity.',
    cards: [
      {
        title: 'Dealer Directory',
        purpose: 'Browse dealer stores already managed in Dealer Bootstrap.',
        status: 'Linked',
        tone: 'green',
        action: 'Open stores',
        existingHref: '/dealer-bootstrap?section=bootstrap',
        existingLabel: 'Dealer Bootstrap',
        summaryKey: 'dealer-stores',
      },
      {
        title: 'Dealer Profiles',
        purpose: 'Create and assign dealer store profiles via existing bootstrap tools.',
        status: 'Linked',
        tone: 'green',
        action: 'Open tool',
        existingHref: '/dealer-bootstrap?section=bootstrap',
        existingLabel: 'Dealer Bootstrap',
        summaryKey: 'dealer-stores',
      },
      {
        title: 'Locations',
        purpose: 'Store location fields live with dealer store records (bootstrap).',
        status: 'Linked',
        tone: 'green',
        action: 'Open stores',
        existingHref: '/dealer-bootstrap?section=bootstrap',
        existingLabel: 'Dealer Bootstrap',
        summaryKey: 'dealer-stores',
      },
      {
        title: 'Contacts',
        purpose: 'Primary contact email and assignments on dealer stores.',
        status: 'Linked',
        tone: 'green',
        action: 'Open tool',
        existingHref: '/dealer-bootstrap?section=bootstrap',
        existingLabel: 'Dealer Bootstrap',
        summaryKey: 'dealer-stores',
      },
      {
        title: 'Visibility & Status',
        purpose: 'Release gates and ops readiness from Dealer Bootstrap.',
        status: 'Linked',
        tone: 'green',
        action: 'Open ops',
        existingHref: '/dealer-bootstrap?section=operations',
        existingLabel: 'Dealer Bootstrap Ops',
        summaryKey: 'ops-verification',
      },
      {
        title: 'Dealer Activity',
        purpose: 'Admin audit log for dealer bootstrap actions.',
        status: 'Linked',
        tone: 'green',
        action: 'Open audit',
        existingHref: '/dealer-bootstrap?section=audit',
        existingLabel: 'Dealer Audit',
        summaryKey: 'dealer-audit',
      },
    ],
  },
  'dealer-operations': {
    id: 'dealer-operations',
    label: 'Dealer Operations',
    icon: '↗',
    description: 'Control onboarding, subscriptions, lead setup, dealer preferences, and activation readiness.',
    route: '/admin/dealer-operations',
    pills: ['Setup', 'Subscriptions', 'Lead Setup', 'Activation'],
    ai: 'Ask about onboarding steps, subscription status, or lead route setup.',
    cards: [
      {
        title: 'Onboarding',
        purpose: 'Manage dealer onboarding workflows and activation readiness.',
        status: 'Linked',
        tone: 'green',
        action: 'Open tool',
        existingHref: '/dealer-bootstrap?section=bootstrap',
        existingLabel: 'Dealer Bootstrap',
        summaryKey: 'dealer-stores',
      },
      {
        title: 'Subscriptions',
        purpose: 'View and manage dealer subscriptions, plans, and pricing.',
        status: 'Stub',
        tone: 'amber',
        action: 'Manage Subscriptions',
      },
      {
        title: 'Lead Setup',
        purpose: 'CNM lead exceptions and ops verification queue.',
        status: 'Linked',
        tone: 'green',
        action: 'Open ops',
        existingHref: '/dealer-bootstrap?section=operations&inbox=cnm',
        existingLabel: 'CNM Exceptions',
        summaryKey: 'cnm-exceptions',
      },
      {
        title: 'Packages & Pricing',
        purpose: 'Manage dealer packages, pricing, discounts, and processing fees.',
        status: 'Stub',
        tone: 'amber',
        action: 'Manage Pricing',
      },
      {
        title: 'Dealer Preferences',
        purpose: 'Store dealer lead, market, contact, and notification preferences.',
        status: 'Linked',
        tone: 'green',
        action: 'Open tool',
        existingHref: '/dealer-beta',
        existingLabel: 'Dealer Beta',
        summaryKey: 'dealer-beta',
      },
      {
        title: 'Activation Status',
        purpose: 'Ops verification and release readiness before enabling access.',
        status: 'Linked',
        tone: 'green',
        action: 'Review activation',
        existingHref: '/dealer-bootstrap?section=operations&inbox=verification',
        existingLabel: 'Ops Verification',
        summaryKey: 'ops-verification',
      },
    ],
  },
  leads: {
    id: 'leads',
    label: 'Leads',
    icon: '◎',
    description: 'Monitor lead inbox, routing, delivery proof, exceptions, and reporting.',
    route: '/admin/leads',
    pills: ['All Leads', 'Delivered', 'Held', 'Failed'],
    ai: 'Ask where leads are going, about routing issues, delivery status, or exceptions.',
    cards: [
      { title: 'Lead Inbox', purpose: 'Global lead inbox across sources and pages.', status: 'Stub', tone: 'amber', action: 'Open Inbox' },
      { title: 'Routing', purpose: 'Inspect and adjust lead routing decisions.', status: 'Stub', tone: 'amber', action: 'Open Routing' },
      { title: 'Delivery', purpose: 'Confirm lead delivery to dealers and CRM destinations.', status: 'Stub', tone: 'amber', action: 'Open Delivery' },
      { title: 'Lead Detail', purpose: 'Open the complete lead record with history.', status: 'Stub', tone: 'amber', action: 'Open Detail' },
      {
        title: 'Exceptions',
        purpose: 'CNM / lead exceptions already tracked in Dealer Bootstrap ops.',
        status: 'Linked',
        tone: 'green',
        action: 'Open queue',
        existingHref: '/dealer-bootstrap?section=operations&inbox=cnm',
        existingLabel: 'CNM Exceptions',
        summaryKey: 'cnm-exceptions',
      },
      { title: 'Lead Reporting', purpose: 'Review lead movement by dealer, source, and status.', status: 'Stub', tone: 'amber', action: 'View Reports' },
    ],
  },
  content: {
    id: 'content',
    label: 'Content',
    icon: '▤',
    description: 'Create, approve, publish, and distribute AutoUnite content.',
    route: '/admin/content',
    pills: ['Drafts', 'Review', 'Scheduled', 'Published'],
    ai: 'Ask about article ideas, drafts, publishing, or distribution copy.',
    cards: [
      {
        title: 'Article Studio',
        purpose: 'Write, edit, and format articles with existing Blog admin tools.',
        status: 'Linked',
        tone: 'green',
        action: 'Open Blog',
        existingHref: '/blog',
        existingLabel: 'Blog admin',
        summaryKey: 'blog',
      },
      {
        title: 'Content Library',
        purpose: 'Organize and manage approved assets and media.',
        status: 'Linked',
        tone: 'green',
        action: 'Open Blog',
        existingHref: '/blog',
        existingLabel: 'Blog admin',
        summaryKey: 'blog',
      },
      {
        title: 'Publishing',
        purpose: 'Publish / unpublish via existing Blog admin.',
        status: 'Linked',
        tone: 'green',
        action: 'Open Blog',
        existingHref: '/blog',
        existingLabel: 'Blog admin',
        summaryKey: 'blog',
      },
      {
        title: 'SEO Setup',
        purpose: 'SEO fields on articles in Blog admin (title, meta, slug).',
        status: 'Linked',
        tone: 'green',
        action: 'Open Blog',
        existingHref: '/blog',
        existingLabel: 'Blog admin',
        summaryKey: 'blog',
      },
      {
        title: 'Approvals',
        purpose: 'Draft vs published workflow in Blog admin.',
        status: 'Linked',
        tone: 'green',
        action: 'Open Blog',
        existingHref: '/blog',
        existingLabel: 'Blog admin',
        summaryKey: 'blog',
      },
      { title: 'Distribution', purpose: 'Track distribution copy and external URLs.', status: 'Stub', tone: 'amber', action: 'Manage Distribution' },
    ],
  },
  reports: {
    id: 'reports',
    label: 'Reports',
    icon: '▥',
    description: 'Measure dealer, lead, content, user, and AutoUnite performance.',
    route: '/admin/reports',
    pills: ['Overview', 'Dealers', 'Leads', 'Content'],
    ai: 'Ask about performance, reporting changes, or what needs attention.',
    cards: [
      { title: 'Overview', purpose: 'View the current AutoUnite performance snapshot.', status: 'Stub', tone: 'amber', action: 'View Overview' },
      { title: 'Dealer Reports', purpose: 'Review dealer activity and setup performance.', status: 'Stub', tone: 'amber', action: 'View Dealer Reports' },
      { title: 'Lead Reports', purpose: 'Review lead volume, delivery, and exceptions.', status: 'Stub', tone: 'amber', action: 'View Lead Reports' },
      { title: 'Content Reports', purpose: 'Measure article views, SEO, and publishing pipeline.', status: 'Stub', tone: 'amber', action: 'View Content Reports' },
      {
        title: 'User Reports',
        purpose: 'User totals from existing Users stats API.',
        status: 'Linked',
        tone: 'green',
        action: 'Open Users',
        existingHref: '/users?tab=users',
        existingLabel: 'Users',
        summaryKey: 'users',
      },
      { title: 'Exports', purpose: 'Download, schedule, and save report views.', status: 'Stub', tone: 'amber', action: 'Open Exports' },
    ],
  },
  users: {
    id: 'users',
    label: 'Users',
    icon: '☷',
    description: 'Manage users, access, preferences, notifications, and account actions.',
    route: '/admin/users',
    pills: ['All Users', 'Admins', 'Dealer Users', 'Notifications'],
    ai: 'Ask about users, roles, notifications, or account status.',
    cards: [
      {
        title: 'User Directory',
        purpose: 'Browse and manage users with the existing Users screen.',
        status: 'Linked',
        tone: 'green',
        action: 'Open Users',
        existingHref: '/users?tab=users',
        existingLabel: 'Users',
        summaryKey: 'users',
      },
      {
        title: 'Profiles',
        purpose: 'Create, update, and manage user profiles.',
        status: 'Linked',
        tone: 'green',
        action: 'Open Users',
        existingHref: '/users?tab=users',
        existingLabel: 'Users',
        summaryKey: 'users',
      },
      {
        title: 'Access & Roles',
        purpose: 'Manage roles, permissions, and access controls.',
        status: 'Linked',
        tone: 'green',
        action: 'Open Users',
        existingHref: '/users?tab=users',
        existingLabel: 'Users',
        summaryKey: 'users',
      },
      {
        title: 'Preferences',
        purpose: 'Vehicle / market prefs live on user records in Users screen.',
        status: 'Linked',
        tone: 'green',
        action: 'Open Users',
        existingHref: '/users?tab=users',
        existingLabel: 'Users',
        summaryKey: 'users',
      },
      {
        title: 'Notifications',
        purpose: 'Notification fields where present on Users; dedicated console later.',
        status: 'Linked',
        tone: 'green',
        action: 'Open Users',
        existingHref: '/users?tab=users',
        existingLabel: 'Users',
        summaryKey: 'users',
      },
      {
        title: 'Account Actions',
        purpose: 'Activate / deactivate and related actions on Users screen.',
        status: 'Linked',
        tone: 'green',
        action: 'Open Users',
        existingHref: '/users?tab=users',
        existingLabel: 'Users',
        summaryKey: 'users',
      },
    ],
  },
  support: {
    id: 'support',
    label: 'Support',
    icon: '☏',
    description: 'Manage support requests, escalations, help content, and resolution history.',
    route: '/admin/support',
    pills: ['Inbox', 'User Requests', 'Dealer Requests', 'Escalated'],
    ai: 'Ask about open issues, dealer requests, user requests, or escalations.',
    cards: [
      {
        title: 'Support Inbox',
        purpose: 'Review incoming support and user requests.',
        status: 'Linked',
        tone: 'green',
        action: 'Open Requests',
        existingHref: '/request',
        existingLabel: 'User Requests',
        summaryKey: 'user-requests',
      },
      {
        title: 'User Requests',
        purpose: 'Track shopper/user request workflows.',
        status: 'Linked',
        tone: 'green',
        action: 'Open Requests',
        existingHref: '/request',
        existingLabel: 'User Requests',
        summaryKey: 'user-requests',
      },
      {
        title: 'Dealer Requests',
        purpose: 'Track dealer-facing requests and beta interest.',
        status: 'Linked',
        tone: 'green',
        action: 'Open Dealer Beta',
        existingHref: '/dealer-beta',
        existingLabel: 'Dealer Beta',
        summaryKey: 'dealer-beta',
      },
      {
        title: 'Escalations',
        purpose: 'Ops verification queue used as interim escalation path.',
        status: 'Linked',
        tone: 'green',
        action: 'Open ops',
        existingHref: '/dealer-bootstrap?section=operations&inbox=verification',
        existingLabel: 'Ops Verification',
        summaryKey: 'ops-verification',
      },
      {
        title: 'Help Content',
        purpose: 'Search queries / governance reference (interim).',
        status: 'Linked',
        tone: 'green',
        action: 'Open Queries',
        existingHref: '/queries',
        existingLabel: 'Search Queries',
        summaryKey: 'queries',
      },
      {
        title: 'Resolution History',
        purpose: 'Closed / contacted states live in User Requests + Dealer Beta.',
        status: 'Linked',
        tone: 'green',
        action: 'Open Requests',
        existingHref: '/request',
        existingLabel: 'User Requests',
        summaryKey: 'user-requests',
      },
    ],
  },
  settings: {
    id: 'settings',
    label: 'Settings',
    icon: '⚙',
    description: 'Control platform defaults, email, SEO/legal, theme, integrations, and admin preferences.',
    route: '/admin/settings',
    pills: ['Platform', 'Email', 'SEO & Legal', 'Integrations'],
    ai: 'Ask about platform defaults, email templates, SEO, legal, themes, or integrations.',
    cards: [
      { title: 'Platform Settings', purpose: 'Global platform defaults and operating preferences.', status: 'Stub', tone: 'amber', action: 'Open Platform' },
      { title: 'Email Settings', purpose: 'Templates and delivery defaults.', status: 'Stub', tone: 'amber', action: 'Open Email' },
      { title: 'SEO & Legal', purpose: 'SEO defaults, legal pages, and compliance copy.', status: 'Stub', tone: 'amber', action: 'Open SEO & Legal' },
      { title: 'Theme & Appearance', purpose: 'Theme tokens and appearance controls.', status: 'Stub', tone: 'amber', action: 'Open Theme' },
      { title: 'Integrations', purpose: 'Provider connections (secrets stay in env — not in UI).', status: 'Stub', tone: 'amber', action: 'Open Integrations' },
      { title: 'Admin Preferences', purpose: 'Admin view preferences and defaults.', status: 'Stub', tone: 'amber', action: 'Open Preferences' },
    ],
  },
};

export function resolveAdminOsTab(param) {
  const key = String(param || '').trim().toLowerCase();
  if (ADMIN_OS_TABS[key]) return ADMIN_OS_TABS[key];
  return ADMIN_OS_TABS.dealers;
}

export function getAdminOsEnvironmentLabel() {
  const raw = String(process.env.NEXT_PUBLIC_ADMIN_ENV || process.env.NEXT_PUBLIC_APP_ENV || '').trim();
  if (/prod/i.test(raw)) return 'Production';
  if (/stag/i.test(raw)) return 'Staging';
  if (/prev/i.test(raw)) return 'Preview';
  if (process.env.NODE_ENV === 'production') return 'Production';
  return 'Preview';
}
